### ISSUE TITLE
Correccion

### ISSUE THREAD

**Issue by AlvaroMartinFernandez** [4GeeksAcademy/bhgeeky-HTML-form-45#1]
El responsive esta perfecto felicidades, aun asi necesito una corrección importante

- [x] el button que de send que es el que envia el formulario tiene que ser de typo submit y deberia de estar dentro del elemento form

<img width="430" alt="image" src="https://github.com/user-attachments/assets/348b016c-f150-46e4-b241-ca74f32cca4e">

**Comment by bhgeeky** [comment]
Ya cambié el botón a tipo submit, lo que a mí me apareció que ya estaba dentro del form como muestro en la foto 
![imagen_2024-11-10_143525607](https://github.com/user-attachments/assets/e4e8acce-a338-4482-a622-b066fa4289be)

**Comment by AlvaroMartinFernandez** [comment]
Perfecto, felicidades
